language: python
python:
  - '3.6'

install: "pip install -r requirements.txt"

before_script:
  - cp .env .env.example

env: DJANGO_SETTINGS_MODULE="ecommerce.settings.development"

services:
  - mysql

script:
  - ./manage.py test
