language: python
python:
  - '3.6'

before_script:
  - cp .env.example .env
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="ecommerce.settings.base"

services:
  - mysql

script:
  - ./manage.py test