# Generated by Django 3.0.5 on 2020-04-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200426_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='color_label',
            new_name='color',
        ),
    ]
