# Generated by Django 3.0.5 on 2020-04-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200426_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('D', 'danger')], max_length=1, null=True),
        ),
    ]
