# Generated by Django 3.0.5 on 2020-04-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200426_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, choices=[('primary-color', 'primary'), ('danger-color', 'danger')], max_length=15, null=True),
        ),
    ]
