# Generated by Django 3.0.5 on 2020-04-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200426_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='color',
            new_name='color_label',
        ),
    ]
