# Generated by Django 3.0.5 on 2020-05-13 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200513_2342'),
        ('core', '0014_auto_20200507_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='users.Address'),
        ),
    ]
